### PR TITLE
Promoting hotfix of #69 to Tier 2

### PR DESCRIPTION
**Pull request by dabrady**
I released a hotfix of #69 to Tier 1 in #72. This continues the deploy of the hotfix to Tier 2.

fyi @pevner-p2 @rhymiz

### CODE REVIEW

**Comment by dabrady** [comment]
Using admin powers to release this hotfix.

**Comment by dabrady** [comment]
Deploy is building: https://semaphoreci.com/prodperfect/prodperfect-keen-tracking-js/branches/canary-tier-2/builds/20

**Review by pevner-p2 — COMMENTED** [review]
Approved.

**Comment by dabrady** [comment]
Deploying:
https://semaphoreci.com/prodperfect/prodperfect-keen-tracking-js/servers/manual-deploy-canary-tier-2-branch-to-canary-tier-2/deploys/8

**Pull request merged**
