### PR TITLE
Hotfix for metadata circular reference issue.  

### PR DESCRIPTION
**Pull request by adewinter**
Switched to using 'safer' `.getAttribute` style.

### CODE REVIEW

**Comment by adewinter** [comment]
@Detect not sure, if we want to get this out soonish I'd vote no (though I would like to add tests for this case at a later juncture)

**Comment by Detect** [comment]
@adewinter can you confirm the CI output is good (some errors even tho it passes)?

**Comment by adewinter** [comment]
@Detect I think those are unrelated to this issue, but I'll double check to verify they also show up in old builds

**Comment by adewinter** [comment]
Yep, unrelated/old warnings.

**Pull request merged**
