### PR TITLE
Ew/fix not collecting element text

### PR DESCRIPTION
**Pull request by ewong26**
I made some changes to the `title`, `title`, and `type` because those fields never used `el.getAttribute` to determine whether to get their values or not: 
https://github.com/ProdPerfect/prodperfect-keen-tracking.js/commit/b11eb0b9402c3aed7e7ffa153452558044f9fb7e#diff-11c2b3af491a10106a39bf99ab73e4e4634355a9d734b58207b46b8d124b5c78L14

Added in a separate ternary instead to return the same result we were looking for and fixed some of the unit tests. I think those were incorrect before which caused the error to slip by us.

Test locally and can see that the element.text gets sent our pipe line:
image

### CODE REVIEW

**Review by adewinter — CHANGES_REQUESTED** [review]
@ewong26 I think we should sync up on what we're trying to do with this commit.  It's not clear why `.getAttribute` would not provide the desired behavior.  For context though, here's the reason that we switched to using `getAttribute('title')` instead of just relying on the direct/shortcut (e.g. `el.title`):

https://prodperfect.slack.com/archives/CJ36JPNGM/p1567805581015900

The tl;dr of that write up is basically if you have a `<form>` element with children elements that have the string 'title', 'text', etc as their _id_ attribute, we're in for a world of hurt if we were to rely on `el.title` form of getting attribute values.

**Comment by adewinter** [comment]
Also digging into this a little more, I'm guessing that this PR is related to [this monday issue](https://prodperfect.monday.com/boards/451757477/pulses/600289139) (please correct me if that's not the case!).

I think the big thing to take note of here is `element.text` may not exist/do what we think it does.  `.text()` is a function within the jQuery library but is not part of vanilla javascript (es5 onwards anyway as far as I can tell).  There's also [`.textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) which _is_ part of the standard, and may be what you want?  Thought we should clarify that before moving forward...

**Comment by ewong26** [comment]
@adewinter yep, it's related to the monday issue. Was not aware of the slack post and going through it now. For using `el.text` instead of `getAttr(el, 'text')` - I was taking a look at the commit (before and after) and for `el.text` returned what we wanted. Let me take a second look.

**Comment by spencersamuel7** [comment]
If element text is going to be pulled, we have to slow-release that to normalization because currently, we do not have it for any customers and that will require a good amount of normalization for each customer

**Comment by rhymiz** [comment]
So, before we spend a bunch more engineering time on this, do we need/care about element.text? It seems like datagroup doesn't use it yet and is not ready to start processing this data. Do we want to throw this in a backlog where it will likely just goes to die?

This is also opens up ways for us to start accidentally collecting PII and that's a big no go.

**Comment by adewinter** [comment]
Yeah.  It's not at all clear to me if there's even a real problem by looking at the monday customer issue linked earlier.   It's 100% true that this is a giant PII/security minefield waiting to happen.

E.g:

```
<body>
    <div>Some cool div!
   
          <form id="secrets">
               <input id="username"></input>
               <input id="password"></input>
 
    </div>
</body>
```

When using something like `.innerText` or `.textContent`, If the user happened to click on the `<div>` we would be sending _all_ of the child text information, including the text in those input fields that may be very sensitive.

So: *if* we decide we actually need this information (which we very much must do before spending any more time here), then we should do some very very careful and thorough planning around how to mitigate the impact to delivery group/analysis engine AND PII leaking mitigation strategies.

**Comment by ewong26** [comment]
I'm all for removing this from the customer issues board and placing it in a backlog somewhere. If it's not affecting us currently and PII is a big concern, this doesn't seem like something we should be looking into.

**Pull request closed without merging**
